// FILE: src/app/components/homeComponents/products.js

const products = [
  {
    id: 1,
    rank: 1,
    name: "iPhone 17 Pro Max",
    image: "/products/iphone-17-pro-max.png",
    emoji: "📱",
    price: 164900,
    oldPrice: 179900,
    discount: 8,
    store: "Flipkart",
    category: "Smartphone",
  },
  {
    id: 2,
    rank: 2,
    name: "Samsung Galaxy S26 Ultra",
    image: "/products/samsung-galaxy-s26-ultra.png",
    emoji: "📲",
    price: 129999,
    oldPrice: 144999,
    discount: 10,
    store: "Amazon",
    category: "Smartphone",
  },
  {
    id: 3,
    rank: 3,
    name: "Nothing Phone (4)",
    image: "/products/nothing-phone-4.png",
    emoji: "⚪",
    price: 34999,
    oldPrice: 39999,
    discount: 13,
    store: "Flipkart",
    category: "Smartphone",
  },
  {
    id: 4,
    rank: 4,
    name: "OnePlus 15",
    image: "/products/oneplus-15.png",
    emoji: "🔴",
    price: 64999,
    oldPrice: 69999,
    discount: 7,
    store: "Amazon",
    category: "Smartphone",
  },
  {
    id: 5,
    rank: 5,
    name: "Google Pixel 10 Pro",
    image: "/products/google-pixel-10-pro.png",
    emoji: "🌐",
    price: 89999,
    oldPrice: 99999,
    discount: 10,
    store: "Croma",
    category: "Smartphone",
  },
  {
    id: 6,
    rank: 6,
    name: "MacBook Air M5",
    image: "/products/macbook-air-m5.png",
    emoji: "💻",
    price: 114990,
    oldPrice: 124990,
    discount: 8,
    store: "Apple Store",
    category: "Laptop",
  },
  {
    id: 7,
    rank: 7,
    name: "AirPods Pro 3",
    image: "/products/airpods-pro-3.png",
    emoji: "🎧",
    price: 24900,
    oldPrice: 29900,
    discount: 17,
    store: "Amazon",
    category: "Audio",
  },
  {
    id: 8,
    rank: 8,
    name: "Sony WH-1000XM6",
    image: "/products/sony-wh1000xm6.png",
    emoji: "🎵",
    price: 29990,
    oldPrice: 34990,
    discount: 14,
    store: "Reliance Digital",
    category: "Audio",
  },
  {
    id: 9,
    rank: 9,
    name: "Nintendo Switch 2",
    image: "/products/nintendo-switch-2.png",
    emoji: "🎮",
    price: 39990,
    oldPrice: 44990,
    discount: 11,
    store: "Vijay Sales",
    category: "Gaming",
  },
  {
    id: 10,
    rank: 10,
    name: "PlayStation 5 Slim",
    image: "/products/playstation-5-slim.png",
    emoji: "🕹️",
    price: 44990,
    oldPrice: 49990,
    discount: 10,
    store: "Croma",
    category: "Gaming",
  },
  {
    id: 11,
    rank: 11,
    name: "Apple Watch Ultra 3",
    image: "/products/apple-watch-ultra-3.png",
    emoji: "⌚",
    price: 89900,
    oldPrice: 99900,
    discount: 10,
    store: "Flipkart",
    category: "Wearable",
  },
  {
    id: 12,
    rank: 12,
    name: "Samsung Galaxy Watch 8",
    image: "/products/samsung-galaxy-watch-8.png",
    emoji: "⌚",
    price: 36999,
    oldPrice: 42999,
    discount: 14,
    store: "Amazon",
    category: "Wearable",
  },
  {
    id: 13,
    rank: 13,
    name: "iPad Air M4",
    image: "/products/ipad-air-m4.png",
    emoji: "📟",
    price: 69900,
    oldPrice: 79900,
    discount: 13,
    store: "Reliance Digital",
    category: "Tablet",
  },
  {
    id: 14,
    rank: 14,
    name: "Dyson Airwrap",
    image: "/products/dyson-airwrap.png",
    emoji: "💨",
    price: 49900,
    oldPrice: 54900,
    discount: 9,
    store: "Vijay Sales",
    category: "Appliance",
  },
  {
    id: 15,
    rank: 15,
    name: "Kindle Paperwhite (2026)",
    image: "/products/kindle-paperwhite-2026.png",
    emoji: "📖",
    price: 16999,
    oldPrice: 19999,
    discount: 15,
    store: "Amazon",
    category: "E-Reader",
  },
];

export default products;