# Generated by Django 6.0.6 on 2026-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('price', models.IntegerField()),
                ('oldPrice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('store', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
